version: "3.9"

services:
  service1:
    build:
      context: ./service_1
    container_name: golang_service
    ports:
      - "8001:8001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 10s
      retries: 3
      start_period: 5s
    networks:
      - app-network

  service2:
    build:
      context: ./service_2
    container_name: python_service
    ports:
      - "8000:8000"  # ✅ fixed line break
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      retries: 3
      start_period: 5s
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    container_name: nginx_reverse_proxy
    ports:
      - "9000:80"
    depends_on:
      - service1
      - service2
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

